### ISSUE TITLE
Method

### ISSUE THREAD

**Issue by norvinnata** [norvinnata/PKl#2]
can you tell me about method?

**Comment by mpuchan** [comment]
### Method 

> 
Method can call only one in readme .md .

**Comment by mpuchan** [comment]
### Adding Method

> try this method 
def  method
puts " ini method"
end

**Comment by norvinnata** [comment]
> ### Adding Method
> > try this method
> > def  method
> > puts " ini method"
> > end

is that the example of method?

**Comment by norvinnata** [comment]
Ok fix#2

**Comment by norvinnata** [comment]
fix #2

**Comment by mpuchan** [comment]
good bye
